/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 shirt.gltf 
Author: DineshThennarasan (https://sketchfab.com/dineshthennarasan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mens-casual-shirt-996c8d78905f433183ac368086580f82
Title: Men's casual Shirt
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/shirt.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Shirt01_Shirt00_1Pattern2D_22597_Shirt00_1Button_FRONT_0.geometry} material={materials.Shirt00_1Button_FRONT} scale={100} />
      <mesh geometry={nodes.Shirt01_Shirt00_1Pattern2D_22592_Shirt00_1Button_FRONT_0.geometry} material={materials.Shirt00_1Button_FRONT} scale={100} />
      <mesh geometry={nodes.Shirt01_Shirt00_1Pattern2D_22591_Shirt00_1Material4782_0.geometry} material={materials.Shirt00_1Material4782} scale={100} />
      <mesh geometry={nodes.Shirt01_Shirt00_1Pattern2D_7658_Shirt00_1Material4782_0.geometry} material={materials.Shirt00_1Material4782} scale={100} />
      <mesh geometry={nodes.Shirt01_Shirt00_1Pattern2D_7659_Shirt00_1Material4782_0.geometry} material={materials.Shirt00_1Material4782} scale={100} />
      <mesh geometry={nodes.Shirt01_Shirt00_1Pattern2D_5118_Shirt00_1Button_FRONT_0.geometry} material={materials.Shirt00_1Button_FRONT} scale={100} />
      <mesh geometry={nodes.Shirt01_Shirt00_1Pattern2D_22589_Shirt00_1Material4782_0.geometry} material={materials.Shirt00_1Material4782} scale={100} />
      <mesh geometry={nodes.Shirt01_Shirt00_1Pattern2D_14923_Shirt00_1Material4782_0.geometry} material={materials.Shirt00_1Material4782} scale={100} />
      <mesh geometry={nodes.Shirt00_1Pattern2D_4228_Shirt01_Shirt00_1Material4782_EY221png_0.geometry} material={materials['Shirt00_1Material4782_EY221.png']} scale={100} />
      <mesh geometry={nodes.Shirt01_Shirt00_1Pattern2D_22596_Shirt00_1Button_FRONT_Button_Texture_00jpg_0.geometry} material={materials['Shirt00_1Button_FRONT_Button_Texture_00.jpg']} scale={100} />
      <mesh geometry={nodes.Shirt01_Shirt00_1Pattern2D_21425_Shirt00_1Material4782_0.geometry} material={materials.Shirt00_1Material4782} scale={100} />
      <mesh geometry={nodes.Shirt01_Shirt00_1Pattern2D_22590_Shirt00_1Material4782_0.geometry} material={materials.Shirt00_1Material4782} scale={100} />
      <mesh geometry={nodes.Shirt01_Shirt00_1Pattern2D_22595_Shirt00_1Button_FRONT_0.geometry} material={materials.Shirt00_1Button_FRONT} scale={100} />
      <mesh geometry={nodes.Shirt01_Shirt00_1Pattern2D_7660_Shirt00_1Material4782_0.geometry} material={materials.Shirt00_1Material4782} scale={100} />
      <mesh geometry={nodes.Shirt01_Shirt00_1Pattern2D_12616_Shirt00_1Material4782_0.geometry} material={materials.Shirt00_1Material4782} scale={100} />
      <mesh geometry={nodes.Shirt01_Shirt00_1Pattern2D_22594_Shirt00_1Button_FRONT_0.geometry} material={materials.Shirt00_1Button_FRONT} scale={100} />
      <mesh geometry={nodes.Shirt01_Shirt00_1Pattern2D_22593_Shirt00_1Button_FRONT_0.geometry} material={materials.Shirt00_1Button_FRONT} scale={100} />
    </group>
  )
}

useGLTF.preload('/shirt.gltf')
